name: CI
on: [push, pull_request]

jobs:
  main:
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-18.04', 'macos-10.15']
        python: ['3.8.12', '3.9.7']

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Project checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install dependencies
        run: make setup

      - name: Check codestyle
        run: make inspect

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
